CREATE DATABASE DEEP;

USE DEEP;

CREATE TABLE USERS(
  IDUSER INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NICKNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL,

  CONSTRAINT UQ_USERNAME_USERS UNIQUE (NICKNAME)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE FORUMS(
  IDFORUM INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IDADM INT(11) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONTENT TEXT NOT NULL,

  CONSTRAINT FK_IDADM_FORUNS FOREIGN KEY (IDADM) REFERENCES USERS (IDUSER)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE COMMENTS(
  IDCOMMENT INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IDUSER INT(11) NOT NULL,
  NICKNAME VARCHAR(32) NOT NULL,
  MESSAGE TEXT NOT NULL,
  MESSAGE_DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_IDUSER_COMMENTS FOREIGN KEY (IDUSER) REFERENCES USERS (IDUSER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Comentários dos forúns';

CREATE TABLE CHAT(
  IDMESSAGE INT(11) NOT NULL,
  IDUSER INT(11) NOT NULL,
  NICKNAME VARCHAR(32) NOT NULL,
  MESSAGE TEXT,
  MESSAGE_DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT FK_IDUSER_CHAT FOREIGN KEY (IDUSER) REFERENCES USERS (IDUSER)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Mensagens do chat';

INSERT INTO USERS (NICKNAME, PASSWORD) VALUES ('Danilo', '123');
INSERT INTO COMMENTS (IDUSER, NICKNAME, MESSAGE) VALUES (1, 'Danilo', 'Olá');
INSERT INTO USERS (NICKNAME, PASSWORD) VALUES ('HALALA', '123');
INSERT INTO COMMENTS (IDUSER, NICKNAME, MESSAGE) VALUES (2, 'HALALA', 'ShowOut and for and no your girlfriend, is my girlfriend');